name: Alert when default milestone

on:
  pull_request:
    types:
      - closed

jobs:

  loging:
    if: ${{ false }} # for debug 
    runs-on: ubuntu-latest
    steps:
      - name: logging event
        run: |
          echo "${{ toJson(github.event) }}"

  check-branch:
    # mergedイベント && masterへのマージ && milestoneが0.0.0 
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.milestone.number == 1 && contains(github.event.pull_request.base.ref, 'main') }}
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }} # for gh CLI
    steps:
      - name: comment pr
        run: |
          cat << EOF > ./comments
            @${{ github.event.pull_request.user.login }}
            hogehoge
          EOF
          gh pr comment -F ./comments ${{ github.event.pull_request.html_url }}

